//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW_EnemyEdit_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class 魔物
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 魔物()
        {
            this.魔物部位 = new HashSet<魔物部位>();
        }
    
        public int Id { get; set; }
        public bool オリジナル { get; set; }
        public bool SW25 { get; set; }
        public bool SW20 { get; set; }
        public string 出典 { get; set; }
        public string 分類 { get; set; }
        public string タグ { get; set; }
        public int LV { get; set; }
        public bool ネームド { get; set; }
        public string 名前 { get; set; }
        public string 名称 { get; set; }
        public string 知能 { get; set; }
        public string 知覚 { get; set; }
        public string 反応 { get; set; }
        public string 言語 { get; set; }
        public string 生息地 { get; set; }
        public int 知名度 { get; set; }
        public int 弱点値 { get; set; }
        public string 弱点 { get; set; }
        public int 先制値 { get; set; }
        public string 移動速度 { get; set; }
        public int 生命抵抗力 { get; set; }
        public int 精神抵抗力 { get; set; }
        public int 穢れ点 { get; set; }
        public int 部位数 { get; set; }
        public string 部位数内訳 { get; set; }
        public string コア部位 { get; set; }
        public string 特殊能力 { get; set; }
        public string 戦利品 { get; set; }
        public string 解説 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<魔物部位> 魔物部位 { get; set; }
    }
}
